### ISSUE TITLE
Redirection after login

### ISSUE THREAD

**Issue by ajm188** [Aaronneyer/the_jolly_advisor#29]
When a user gets denied access because they are not signed in, we store the url they were trying to get to. When they then sign in, we redirect them to that url.

However, a user can go to a bunch of different pages between getting an access denied and actually signing in, so this redirection may not put them on the page they wanted or were expecting.

I think instead we should store the last url requested by the user, and redirect them there when they sign in.

**Comment by Aaronneyer** [comment]
I'm confused. How would a user go to a bunch of different pages between getting access denied and signing in?
Don't they get immediately redirected to the sign-in page once they get access denied, not leaving any real space for pages in the middle?

**Comment by ajm188** [comment]
You're right. I just realized I didn't describe what actually happened so my bad.
Here's what I did:
- tried to go to /wishlist, got redirected to sign in. good
- signed in, got redirected to /wishlist. good
- went to home page, signed out, signed back in (auth is cached so you don't get redirected to the sign in), got redirected to /wishlist. bad

**Comment by StephHippo** [comment]
So we need to clear the cache on sign out.

**Comment by Aaronneyer** [comment]
Ah right. So we're grabbing `session[:was_at]`, which is stateful. Bad.
Perhaps we can use a query parameter that gets passed through CAS?

**Comment by ajm188** [comment]
I think Steph's solution is easier, with one modification. Pass the current url as a param to the login action, then redirect to whatever is in the session or whatever was passed (defaulting to root). and also clear the cache.

**Comment by Aaronneyer** [comment]
So the real problem here is that when we click the login button, we aren't setting `session[:was_at]`, but I don't think that's really a thing that can be done after it is clicked, which is why I think passing it as a query parameter makes sense.

Clearing the cache isn't going to work in every case. For example, what happens if a user exits out when they are on the case SSO page, then we never clear the cache.

I have a PR done that implements it as a query, I can push that up so you can get a look.

**Comment by Aaronneyer** [comment]
Woops, went home for the weekend and forgot to actually push this up.
https://github.com/Aaronneyer/the_jolly_advisor/pull/31

**Comment by Aaronneyer** [comment]
Fixed via #31
